HELP_TXT = '''
/description - описание бота
/help - команды бота
'''

DESCRIPTION_TXT = '''
<em>Бот, который отправляет смешнявки в рандомные промежутки времени</em>
'''

SET_STICKERS_ID = [
    'CAACAgIAAxkBAAEG9P9jpNiMifSAn8-VFl1E536OIm-YcwAC7ycAAtK88Uj3Rb40jg4o1iwE',
    'CAACAgIAAxkBAAEG9QFjpNmCRE3C9E3Z219gBxmo3Sm84AACniAAAsXR-Ug45YBFpGYIuSwE',
    'CAACAgIAAxkBAAEG9QJjpNmDDu-9o_z1V-ffbWTOn0dz5gACqSUAArUs8UhPraDLTyOWZywE',
    'CAACAgIAAxkBAAEG9QRjpNmDWeJk8xL_c7FDSTdYT2ayWAACFSIAArKq-Ej52M7ZRHCBAiwE',
    'CAACAgIAAxkBAAEG9QdjpNmOon2-nQcYx_k_sKGq4RxNzAACjCEAAvlD8Ugcf8omMRpQaiwE',
    'CAACAgIAAxkBAAEG9QljpNmVHxLaqifVpXp9ny81AjhbiQAC2yUAAjYo8UiCs2AdDtwZCiwE',
    'CAACAgIAAxkBAAEG9QpjpNmWYIO9Pn01sJjC1UKYoVOPzwACsygAAmYt8EhNcQPwX_bBNCwE',
    'CAACAgIAAxkBAAEG9QtjpNmWXoSFj573IMwMisL6oPpkggAClSsAAn7E8EgarJ-WBdNTfCwE',
    'CAACAgIAAxkBAAEG9QxjpNmW6VDu2mlBXbdPu94ETxfszAACECkAAuzJ8EiiSET7oeE_6SwE',
    'CAACAgIAAxkBAAEG9RFjpNo_w0YGtKGc-0MD8BP-Qgtd5gACaSgAAjgm8Eiw-bfz1561ZSwE',
    'CAACAgIAAxkBAAEG9RJjpNpAuNVL8RsKAyUAAX7nRmHh4DMAAmkiAAL0yfFInoN-4BaPXZgsBA',
    'CAACAgIAAxkBAAEG9RNjpNpApYPDM1uImmEnj5C_X9BhrwAC5yQAAoXv8UjdArmEpLGKICwE',
    'CAACAgIAAxkBAAEG9RdjpNqAbg0KI2DDKvNQP1auCAibugACmCIAAmNh8Ug8EdDDIvJCsCwE',
    'CAACAgIAAxkBAAEG9RhjpNqAO2w7q6m-nZx7m26vB3UeRgACYCUAAr788EgmyyDB46jSiSwE',
    'CAACAgIAAxkBAAEG9RljpNqAmqdOmkPeLMP3NGKgxtZWzQACEiYAAtLp8UjdWsZCLDA_HywE',
    'CAACAgIAAxkBAAEG9SBjpNqwbHW1WnxpEYTPV0lkcU4UswACRCEAAr3K-EjDubDYOO1aQywE',
    'CAACAgIAAxkBAAEG9SFjpNqwZeSLKTO_X-Mdl7EBage-YwACyB8AAgR9IUlw7NX8e9rGfiwE',
    'CAACAgIAAxkBAAEG9SJjpNqxoyG8jJq5sMSTr5YH8n4uAgACZyAAAt3SIUkZGbzA7L3VXSwE',
    'CAACAgIAAxkBAAEG9SpjpNwzb9jsDBKpqR7SHolv9U71ZgAC-CoAArpLIEkLTz9r08MtwiwE',
    'CAACAgIAAxkBAAEG9StjpNw0ndMtQVBMnwdIZ1Lyh51CcwACMyAAAo6QIUnpSeXvxQHgXywE',
    'CAACAgIAAxkBAAEG9SxjpNw0vuNdxUqFlO5vZe6UzKmoHQAC0iUAAmq4IEnsFjLFJ6oKcSwE',
    'CAACAgIAAxkBAAEG9TBjpNxjPSaT-haEebLJDBh9lApM2gACaCcAAluxGUmx6DMOBqwb2CwE',
    'CAACAgIAAxkBAAEG9TFjpNxk_WC7MuekBSti4mDLzL5nFAAClycAAtT1GEkAARXVl6BUjsUsBA',
    'CAACAgIAAxkBAAEG9TJjpNxkErEg93klXNLhVWYrQXOR2QACySYAAnWdGUkH-FW7fMuuyCwE',
    'CAACAgIAAxkBAAEG9TZjpNyTl04BLjYjLZRdxU4_jlczBAACXCcAAgg6IEnoiWnuJqMOXSwE',
    'CAACAgIAAxkBAAEG9TdjpNyTc9-MCwn-gwysgdvne4xBIQACIioAAvvKGEkcYIng_7ByfCwE',
    'CAACAgIAAxkBAAEG9ThjpNyU17cTWDyhTyBZgRiagz_PqgACviUAAknSGEnLCW55sCTx0CwE',
    'CAACAgIAAxkBAAEG9TljpNyU2ZVlu2dLgbsp27eGZtRPKAACDiYAAsZxGUkVj6RcXazSoCwE',
    'CAACAgIAAxkBAAEG9T5jpN0JgA0TBNjTgI_PXP6lnMTU-wACzyUAAohiGEkzM5goTcz-OCwE',
    'CAACAgIAAxkBAAEG9T9jpN0JWYD0CkkqM7ZXm8y9iVi58wACJE4AAlz9IUn_KGSQK91kRCwE',
    'CAACAgIAAxkBAAEG9URjpN0hjtoaa8XX7VTtvL9IAqOf5gAC4SkAAk-1GEklS38OBe7oYCwE'
]

KIR_ID = 523118031